# a list of all the programs in your package
EXECUTABLES = capd-ddes-DDECommon

# a list of all your units to be linked with your programs
OTHERS = 

EXTRALINKEROPTIONS=-lboost_unit_test_framework

# run the true Makefile
include ../makefile-run.mk

