# a list of all the programs in your package
EXECUTABLES = statmatrix convmatrix convvector growvector mulvector splitvector invmatrixtest vectorcmp matrixcmp midmatrix vectorhull crmatrix rmatrix gencoords

# a list of all your units to be linked with your programs
OTHERS = 

# run the true Makefile
include ../makefile-run.mk