# this will make it into a separate subfolder of a given name, trailing / is important!) 
PACKAGE = mackey-glass-stable-periodic/

# the defaut output folder (defined above) is ignored if those two are given (please keep trailing '/' !)
OUTDIR = ./bin/
OBJDIR = ./.obj/

# a list of all the programs to compile (from this directory), separated by single space.
# i.e. .cpp files that contain main() function.
#EXECUTABLES = nonrig-find rig-prove
EXECUTABLES = nonrig-find

# a list of all your units to be linked with your programs (other .cpp files), separated by single space
# i.e. all other .cpp files that does not have main() inside.
#OTHERS = nonrig-setup rig-setup
OTHERS = nonrig-setup

# 'run' the true Makefile
include ../makefile-run.mk