# a list of all the programs in your package
EXECUTABLES = cubeset_tests tests

# a list of all your units to be linked with your programs
OTHERS = 

EXTRALINKEROPTIONS=

# run the true Makefile
include ../makefile-run.mk

